[package]
name = "primesieve_sys"
version = "0.0.1"
authors = ["Alexander Ronald Altman <alexanderaltman@me.com>"]
build = "build.rs"
links = "primesieve"

[dependencies]
libc = "0.2.15"

[build-dependencies]
gcc = "~0.3.32"
